import "../globals.css";
import Header from "@/components/shared/header";
import Sidebar from "@/components/shared/sidebar";
import ProviderWrapper from "@/utils/store/ProviderWrapper";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#e0dbd4]">
        <ProviderWrapper>
          <Header />
          <div className="h-full flex flex-row box-border px-8 py-4 gap-8 w-full">
            <Sidebar />
            {children}
          </div>
        </ProviderWrapper>
      </body>
    </html>
  );
}
